### ISSUE TITLE
Plugin doesn't respond

### ISSUE THREAD

**Issue by amruta-meh** [PratyushTripathy/COINS#3]
I have tried using both the versions of the plugin on a small graph in QGIS 3.14 and QGIS 3.10. It remains at 0% and stops responding. That's the shapefile I am using. How to resolve? 
https://drive.google.com/file/d/1pPt3AlnKh0sjdMeR6kfAV5NI4JBcwc4z/view?usp=sharing

**Comment by PratyushTripathy** [comment]
@amruta-meh The shapefile seems to be working fine on my computer. I tried it on two different systems and it works well. Could you please check your QGIS installation once or try on a different PC? Here is the output (Jenks 4 classes) and the generated file.

![image](https://user-images.githubusercontent.com/29382796/122938703-9c8a6900-d390-11eb-9606-54a143c7fcc1.png)
[milan_roads_hierarchy.zip](https://github.com/PratyushTripathy/COINS/files/6694835/milan_roads_hierarchy.zip)

**Comment by amruta-meh** [comment]
Hello Prayush,
Thank you for resolving the issue. The plugin has been working after I
reinstalled QGIS.
Regards,
Amruta
